### ISSUE TITLE
event timestamp format

### ISSUE THREAD

**Issue by taylorhickem** [taylorhickem/tg-hours#4]
## mismatched timestamp format

starting from morning of 2023-05-18 exception mismatched timestamp in _stop_ field. Previous day report ran without exceptions.

### exception
```
Traceback (most recent call last):
  File "C:\Users\taylo\AppData\Local\Programs\Python\Python36\Lib\tg-hours\tghours\toggl.py", line 257, in <lambda>
    std['stop_date'] = std['stop'].apply(lambda x: utc_str_to_local_datetime(x, 'stop').date())
  File "C:\Users\taylo\AppData\Local\Programs\Python\Python36\Lib\tg-hours\tghours\toggl.py", line 289, in utc_str_to_local_datetime
    utc_timestamp = dt.datetime.strptime(utc_str, datetime_format)

ValueError: time data '2023-05-18T00:33:17+00:00' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by taylorhickem** [comment]
the letter __Z__ is shorthand for Zulu time or +00:00
Toggle uses both formats +00:00 or Z so 

solution is to replace 'Z' with '+00:00'

tghours/toggl.py

```
...
def utc_str_to_local_datetime(utc_str, format_code):
    utc_str = utc_str.replace('Z', '+00:00')
    datetime_format = TOGGL_TIMESTAMP_FORMAT
    utc_timestamp = dt.datetime.strptime(utc_str, datetime_format)
    ...
```

**Comment by taylorhickem** [comment]
see #6
